name: MLOps Pipeline

on:
  workflow_dispatch:
    inputs:
      run_all:
        description: 'Run all jobs'
        required: false
        default: 'true'
  release:
    types: [ created ]
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

permissions:
  contents: read

jobs:
  data-processing:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Data Processing
      run: |
        python src/data/run_processing.py \
          --input data/raw/house_data.csv \
          --output data/processed/cleaned_house_data.csv

    - name: Run Feature Engineering
      run: |
        python3 src/features/engineer.py \
          --input data/processed/cleaned_house_data.csv \
          --output data/processed/featured_house_data.csv \
          --preprocessor models/trained/preprocessor.pkl

    - name: Upload processed data artifact
      uses: actions/upload-artifact@v4
      with:
        name: processed-data
        path: data/processed/featured_house_data.csv

    - name: Upload processed data artifact
      uses: actions/upload-artifact@v4
      with:
        name: preprocessor.pkl
        path: models/trained/preprocessor.pkl

  model-training:
    needs: data-processing
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Download processed data artifact
      uses: actions/download-artifact@v4
      with:
        name: processed-data
        path: data/processed/

    - name: Setup MLflow
      run: |
        docker pull ghcr.io/mlflow/mlflow:latest
        docker run -d -p 5555:5000 --name mlflow_server ghcr.io/mlflow/mlflow:latest \
          mlflow server --host 0.0.0.0 \
          --backend-store-uri sqlite:///mlflow.db \
          --default-artifact-root /tmp/mlruns

    - name: Wait for MLflow to be ready
      run: |
        for i in {1..10}; do
          if curl -s http://localhost:5555/health >/dev/null; then
            echo "MLflow is up!"
            exit 0
          else
            echo "Waiting for MLflow to start..."
            sleep 5
          fi
        done

    - name: Run Model Training
      run: |
        python3 src/models/train_model.py   \
        --config configs/model_config.yaml   \
        --data data/processed/featured_house_data.csv   \
        --models-dir models   \
        --mlflow-tracking-uri http://localhost:5555

    - name: Upload trained model
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: models/

    - name: Cleaning MLflow
      run: |
        docker stop mlflow_server
        docker rm mlflow_server
        docker rmi ghcr.io/mlflow/mlflow:latest

  build-and-publish:
    needs: model-training
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4

    - name: Download trained model
      uses: actions/download-artifact@v4
      with:
        name: trained-model
        path: models/trained/

    - name: Download preprocessor
      uses: actions/download-artifact@v4
      with:
        name: preprocessor.pkl
        path: models/trained/

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      run: |
        COMMIT_SHA=$(echo ${{ github.sha }} | cut -c 0-7)
        docker build -t docker.io/${{ vars.DOCKERHUB_USERNAME }}/house-price-model:${COMMIT_SHA} -f ./Dockerfile .
        docker run -d -p 8000:8000 --name test-api docker.io/${{ vars.DOCKERHUB_USERNAME }}/house-price-model:${COMMIT_SHA}
        for i in {1..10}; do
          if curl -s http://localhost:8000/health >/dev/null; then
            echo "API is up!"
            break
          else
            echo "Waiting for API to start..."
            sleep 5
          fi
        done
        docker logs test-api

    - name: Cleanup test container
      run: |
        docker stop test-api || true
        docker rm test-api || true

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name : Push image to Docker Hub
      run: |
        COMMIT_SHA=$(echo ${{ github.sha }} | cut -c 0-7)
        docker tag docker.io/${{ vars.DOCKERHUB_USERNAME }}/house-price-model:${COMMIT_SHA} docker.io/${{ vars.DOCKERHUB_USERNAME }}/house-price-model:latest
        docker push docker.io/${{ vars.DOCKERHUB_USERNAME }}/house-price-model:${COMMIT_SHA}
        docker push docker.io/${{ vars.DOCKERHUB_USERNAME }}/house-price-model:latest
        
